export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const REGISTER_USER = 'REGISTER_USER';

// EVSE TYPES
export const EVSE_LOADING = 'EVSE_LOADING';
export const GET_EVSES = 'GET_EVSES';
export const GET_EVSE = 'GET_EVSE';

// LOCATION TYPES
export const LOCATION_LOADING = 'LOCATION_LOADING';
export const GET_LOCATIONS = 'GET_LOCATIONS';
export const CREATE_LOCATION = 'CREATE_LOCATION';

// VEHICULE TYPES
export const VEHICULE_LOADING = 'VEHICULE_LOADING';
export const GET_VEHICULES = 'GET_VEHICULES';

// CONNECTOR TYPES
export const CONNECTOR_LOADING = 'CONNECTOR_LOADING';
export const GET_CONNECTORS = 'GET_CONNECTORS';
